### ISSUE TITLE
concat-stream-1.5.2 site unreachable

### ISSUE THREAD

**Issue by gxvigo** [watson-developer-cloud/assistant-simple#159]
Hi There, 

I am building an app using watson-developer-cloud but npm install fails due to the following site unavailability:
http://173.192.225.82:8080/c/concat-stream/_attachments/concat-stream-1.5.2.tgz

**Comment by germanattanasio** [comment]
delete the `package-lock.json` file and run `npm install` again.

**Comment by gxvigo** [comment]
Thanks, it worked like a charm.

Cheers.
