### ISSUE TITLE
IFrame version - parentpage interaction

### ISSUE THREAD

**Issue by germanAdrian** [watson-developer-cloud/assistant-simple#161]
Hey,

I am currently trying to build an Iframe version that is supposed to interact with the parent page.

My plan is to perform actions on the page according to the detected intent & entity values.

My problem: I can not figure out how to access the answer (response) coming from IBM Assistant.
Is there any possibility to access this Object?

Thank you for your support in advance.

**Comment by germanattanasio** [comment]
You can't access the data from the iframe unless you are running in the same domain. Try deploying this app instead of using the deployed version as iframe.

See https://stackoverflow.com/questions/1451208/access-iframe-elements-in-javascript
