### ISSUE TITLE
Add GDPR Language to Stand Alone Demo Pages

### ISSUE THREAD

**Issue by mamoonraja** [watson-developer-cloud/assistant-simple#165]
**Context:**
GDPR will go into effect on May 25th; we need the demos to display the following language in order to make them compliant with the law:

`This system is for demonstration purposes only and is not intended to process Personal Data. No Personal Data is to be entered into this system as it may not have the necessary controls in place to meet the requirements of the General Data Protection Regulation (EU) 2016/679.`

For more information see: https://github.ibm.com/Watson/developer-experience/issues/4342

**How to update:**
- Add disclaimer as text.

**Comment by mamoonraja** [comment]
@stevenpkg Can we prioritize this issue? Please let me know if you need any help from our team on any of the demos.

**Comment by stevenpkg** [comment]
Hi @mamoonraja I maintain about 3+ Watson Assistant and Discovery demo's, I am not sure if any of then use watson-react-components, can I just look in the package.json file, or is it more complete then that? These are the main demos I look after:

https://github.com/watson-developer-cloud/assistant-simple
https://github.com/watson-developer-cloud/car-dashboard
https://github.com/watson-developer-cloud/assistant-with-discovery

**Comment by stevenpkg** [comment]
@germanattanasio 
Hi @mamoonraja can we have a talk on my Tuesday morning, or a time that your free. I need to fully understand what you need me to do.

**Comment by mamoonraja** [comment]
@stevenpkg We need to add the disclaimer, see https://natural-language-classifier-demo.ng.bluemix.net/ for example. 

you don't even need to update `package-lock.json`.

**Comment by stevenpkg** [comment]
@mamoonraja I do not have edit permission for the conversation demo github pages @germanattanasio can you give me permission to make the changes

**Comment by mamoonraja** [comment]
@stevenpkg which demo? I just checked and you have write access to https://github.com/watson-developer-cloud/assistant-simple, https://github.com/watson-developer-cloud/car-dashboard and https://github.com/watson-developer-cloud/assistant-with-discovery

**Comment by germanattanasio** [comment]
You can also fork the repo and do a PR.

**Comment by stevenpkg** [comment]
Are we adding the disclaimer to the GitHub description for each demo, or are we adding the disclaimer to the readme? If it is the readme then no problem, but I see no edit button next to GitHub page description to edit.

**Comment by stevenpkg** [comment]
![How does this look](https://user-images.githubusercontent.com/23624214/39555210-dc6d415e-4eba-11e8-98e7-288baf7c1a10.png)

**Comment by mamoonraja** [comment]
@stevenpkg Please take a look at https://github.com/watson-developer-cloud/natural-language-classifier-nodejs/pull/56. You can do something like that.

**Comment by stevenpkg** [comment]
![screen shot 2018-05-08 at 9 07 41 am](https://user-images.githubusercontent.com/23624214/39729474-5b95b208-529f-11e8-9e38-1c635abdc0b4.png)

@mamoonraja If you are happy with this I will do the same to car dashboard and assistant with discovery

**Comment by stevenpkg** [comment]
@desmarchris have created a pull request for all 3 demos, assistant-simple, car dashboard, and assistant-with-discovery

**Comment by germanattanasio** [comment]
@mamoonraja please assist @stevenpkg reviewing and merging this PR if is ready

**Comment by mamoonraja** [comment]
All the PR's were merged earlier today.

@stevenpkg Can you deploy the latest version for https://github.com/watson-developer-cloud/assistant-with-discovery because I remember you use to deploy it manually.

**Comment by stevenpkg** [comment]
@mamoonraja I have created and tested assistant-with-discovery-new and all okay. Will you change URLs and rename etc?

**Comment by mamoonraja** [comment]
`assistant-with-discovery` is updated.
