### ISSUE TITLE
App fails to run locally (401 Unauthorized)

### ISSUE THREAD

**Issue by MohammedFadin** [watson-developer-cloud/assistant-simple#170]
Hi,

Since the new update, I'm not able to run application locally. I keep getting the below messages from browser console. 

It's worth to mention that the application works fine on the cloud but not locally.

<img width="1438" alt="screen shot 2018-06-03 at 3 17 14 pm" src="https://user-images.githubusercontent.com/2106384/40886500-a5ba0468-6741-11e8-9c4b-e19a8b90c8fa.png">

**Comment by germanattanasio** [comment]
It's probably the credentials.
Make sure you have an `.env` file with valid credentials. Check the README for more information.

**Comment by Oliver-I** [comment]
@MohammedFadin Are you still experiencing this issue?
