### ISSUE TITLE
Import csv not working and the error statement is not helping

### ISSUE THREAD

**Issue by TarunTater** [watson-developer-cloud/assistant-simple#171]
I have a csv file as specified in the format for the csv for importing intents in the Watson conversation service. The format specified is example1, intent1. When I upload a CSV file with this template, I get the error : 

> There was an error parsing your csv file. Please review the contents of the file to ensure that it is correctly formatted.

Since I cannot see any error in my file, is there a way to understand better why this error is thrown?

**Comment by Oliver-I** [comment]
@TarunTater Are you still experiencing this issue?

**Comment by TarunTater** [comment]
Missed the notification somehow. It was a problem with the plan. I had more intents than the limit for my plan and it was giving this error. Maybe a better framed error response could help. Thanks :)
