### ISSUE TITLE
Error: Argument error: username and password are required for LANGUAGE TRANSLATOR V2 unless use_unauthenticated is set

### ISSUE THREAD

**Issue by priyankaghule2906** [watson-developer-cloud/assistant-simple#172]
I am also facing the same issue. App is not starting while restaging and throwing error "Error: Argument error: username and password are required for LANGUAGE TRANSLATOR V2 unless use_unauthenticated is set". 

The Project which I downloaded from below link does not contain .env file
https://github.com/ibmecod/watson-parrot-nodejs/archive/master.zip

[and I use sso password for logging in to the bluemix account]

Below the directory structure

 Directory of c:\cloud\watson-parrot-nodejs-master

06/16/2018  11:48 PM    <DIR>          .
06/16/2018  11:48 PM    <DIR>          ..
06/16/2018  11:48 PM               563 .cfignore
06/16/2018  11:48 PM               563 .gitignore
06/16/2018  11:48 PM             1,513 app.js
06/16/2018  11:48 PM    <DIR>          bin
06/16/2018  11:48 PM               210 Dockerfile
06/16/2018  11:48 PM             1,109 LICENSE
06/20/2018  09:21 PM               178 manifest.yml
06/16/2018  11:48 PM               506 package.json
06/16/2018  11:48 PM    <DIR>          public
06/16/2018  11:48 PM             4,564 README.md
06/16/2018  11:48 PM               177 repository.yaml
06/16/2018  11:48 PM    <DIR>          routes
06/16/2018  11:48 PM               847 smart-parrot-deployment.yaml
06/16/2018  11:48 PM    <DIR>          views
              10 File(s)         10,230 bytes
               6 Dir(s)  311,881,211,904 bytes free
Please help me solve this issue.

Thanks,
Priyanka

**Comment by Oliver-I** [comment]
@stevenpkg Can you look at this?
