### ISSUE TITLE
add messaging for using in Sydney and IAM

### ISSUE THREAD

**Issue by mitchmason** [watson-developer-cloud/assistant-simple#173]
Please at least add a message for how to use with IAM. To do so, two things are needed.
1. Update app.js to look for url and api-key instead of username/password
```
url: process.env.ASSISTANT_URL || '<url>',
 iam_apikey: process.env.ASSISTANT_IAM_APIKEY || '<iam_apikey>',
```
2. Update .env to give this info
```
# Environment variables
WORKSPACE_ID=<workspace-id>
ASSISTANT_URL=https://gateway-syd.watsonplatform.net/assistant/api
ASSISTANT_IAM_APIKEY=<api-key>
```
Eventually we need to update the app to just work for all regions/authentications, but that can come over time

**Comment by Oliver-I** [comment]
@stevenpkg Can you look into this?

**Comment by stevenpkg** [comment]
@mitchmason I can look into this, may be we can we can leave username and password, but if you fill out .env with URL and IAM_APIKEY it will use that?

**Comment by mitchmason** [comment]
Yes please do not break what is already working in the us and Germany. You can just add a note to the readme of what I said above.
Or if you can make it so it uses whatever you provide that would be great, but obviously more work on your guys side.

We should do this for all the sample apps as well for anyone in Sydney.

**Comment by stevenpkg** [comment]
@michelle-miller From what I can see you do not need ASSISTANT_URL?

var watsonAssistant = new AssistantV1({
    version: '{version}',
    iam_apikey: '{iam_api_key}'
  });

**Comment by mitchmason** [comment]
The url for Sydney is different so I’m pretty sure it currently assumes us south. For iam it’s in Sydney

**Comment by mitchmason** [comment]
This has just grown... us east also uses IAM, and we need instructions for using across all different regions and auth processes.

**Comment by stevenpkg** [comment]
Until I add the extra IAM parameters in the .env and add the code to use it, no Assistant demos can use IAM API key. Once in, you should just need your IAM API-KEY and URL for the region.

**Comment by stevenpkg** [comment]
This has been completed. See https://github.com/watson-developer-cloud/assistant-simple/pull/175

**Comment by mbamba71** [comment]
Thanks @stevenpkg. @mitchmason can you please confirm this is done and sample apps are good for RC/IAM?

**Comment by mitchmason** [comment]
At a glance it looks good. If I hear any negative feedback we can reopen

**Comment by stevenpkg** [comment]
I will work on Car Dashboard next
