### ISSUE TITLE
401 Unauthorized when accessing watson assistant service using apikey

### ISSUE THREAD

**Issue by YathendraPrasad** [watson-developer-cloud/assistant-simple#176]
I am trying to access the watson assistant service in sydney region using apikey .

My assumption is that the Swagger JSON will be same across all the regions for the watson assistant service .

So i am using the JSON from 
https://watson-api-explorer.ng.bluemix.net/listings/conversation-v1.json .

As part of our product we generate adapter to access assistant service . When ever i try access service , i am getting 401 unauthorized even though i pass the apikey in Authorization Header as per your defined JSON .

This is My HttpHeader request ..

Accept: application/json
Authorization : HIdLuTGbRlMopuKJ-zU97XdFeEHJISZIU5i-h2wSuCpZ
Content-Type: application/json
User-Agent: Swagger-Codegen/1.0.0/java

And in your JSON , the security definition  is like ....

 "securityDefinitions": {
    "basicAuth": {
      "type": "basic"
    },
    "IAM": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  }

So , when i try the same thing using CuRL command it is working 

curl -X GET "https://gateway-syd.watsonplatform.net/assistant/api/v1/workspaces?page_limit=100&include_count=false&include_audit=false&version=2018-02-16" -H  "accept: application/json" -u  "apiKey":"HIdLuTGbRlMopuKJ-zU97XdFeEHJISZIU5i-h2wSuCpZ"

But my question is i see the apikey has to be set in the authorization header , but when i try CuRL with same header option like 

curl -X GET "https://gateway-syd.watsonplatform.net/assistant/api/v1/workspaces?page_limit=100&include_count=false&include_audit=false&version=2018-02-16" -H  "accept: application/json" -H  "Authorization:HIdLuTGbRlMopuKJ-zU97XdFeEHJISZIU5i-h2wSuCpZ"

It is not working...

Please need your input on this .

Note : We are generating Swagger Client code to access the service

**Comment by YathendraPrasad** [comment]
@stevenpkg : Please help me to resolve the issue reported above .

**Comment by stevenpkg** [comment]
@YathendraPrasad I not sure I can help you here, @germanattanasio can you advise

**Comment by YathendraPrasad** [comment]
I was able to get the answer for my question from WDC-Conversation slack channel .
