### ISSUE TITLE
Documentation in step 7 is incorrect.

### ISSUE THREAD

**Issue by maclean-stu** [watson-developer-cloud/assistant-simple#182]
The documentation instructions for authentication setup is misleading. The example shows IAM as being in the US South and Basic as being in the Sydney regions and as a consequence also confused the gateways. However, Basic is in US South and IAM is used in Sydney. This has caused some confusion for new Sydney based customers trialing the service sample.

I have updated the text below to correct the confusion.

Step 7. 
Example .env file that configures the apikey and url for a Watson Assistant service instance hosted in the Sydney region:

ASSISTANT_IAM_APIKEY=X4rbi8vwZmKpXfowaS3GAsA7vdy17Qh7km5D6EzKLHL2
ASSISTANT_URL=https://gateway-syd.watsonplatform.net/assistant/api

If your service instance uses username and password credentials, add the ASSISTANT_USERNAME and ASSISTANT_PASSWORD variables to the .env file.

Example .env file that configures the username, password, and url for a Watson Assistant service instance hosted in the US South region:

ASSISTANT_USERNAME=522be-7b41-ab44-dec3-g1eab2ha73c6
ASSISTANT_PASSWORD=A4Z5BdGENrwu8
ASSISTANT_URL=https://gateway.watsonplatform.net/assistant/api

Add the WORKSPACE_ID to the previous properties
WORKSPACE_ID=522be-7b41-ab44-dec3-g1eab2ha73c6

**Comment by Oliver-I** [comment]
@stevenpkg FYI
