### ISSUE TITLE
weird gap on Firefox and chrome

### ISSUE THREAD

**Issue by mitchmason** [watson-developer-cloud/assistant-simple#187]
when viewing in Firefox or chrome, there is a large gap between the chat and the json on the right.

**Comment by Oliver-I** [comment]
@stevenpkg Can you take a look at this?

**Comment by Beastjdhr** [comment]
Hey, I'd like to work on this issue.

**Comment by stevenpkg** [comment]
I am currently looking into this

**Comment by stevenpkg** [comment]
@mitchmason  The chat area on the left is centred in the leftover space from the JSON area on the right. I think this is okay. Otherwise we would have to left or right justify the chat area, or have the chat area take up all the available space. My preference is to leave it as it is?

**Comment by mitchmason** [comment]
It was really bothering me before but I dont see anything too bad now that I'm looking again, ignore for now
