### ISSUE TITLE
Can't clone any of the ".filename" files to my local machine

### ISSUE THREAD

**Issue by Confidenceiskey** [watson-developer-cloud/assistant-simple#190]
I'm following the instruction in the readme and am on step 6.

I forked the project to my repository and git cloned to my local machine. However, when I open up the project folder on my local machine it is missing all the files in the picture below.

<img width="160" alt="image" src="https://user-images.githubusercontent.com/22338256/44494413-fcd98900-a641-11e8-812b-b9aa323df526.png">

How can you get that .env.example file locally, so I can make a copy of it & input all my credentials?

Thanks.

**Comment by germanattanasio** [comment]
Some operative systems thread files that start with `.` as hidden files.

If you are using mac you can change that following the steps here https://ianlunn.co.uk/articles/quickly-showhide-hidden-files-mac-os-x-mavericks/

**Comment by Confidenceiskey** [comment]
@germanattanasio, thank you so much! This was the exact problem!

I didn't realize Macs hide files that start with a ```"."``` by default.

Cheers
