### ISSUE TITLE
Error with npm install and npm start

### ISSUE THREAD

**Issue by sagarvadodaria** [watson-developer-cloud/assistant-simple#192]
Hi.I am new to this, hence please bear with me. 
IS this only supported for linux? I am running this app in Windows Server 2012 and get the error as below. I have updated npm and nvm. 

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\****\AppData\Roaming\npm-cache\_logs\2018-09-06T23_32_
32_255Z-debug.log

**Comment by sagarvadodaria** [comment]
F:\Bot Samples\ibm\assistant-simple-master>npm start

> @ibm-watson/assistant-simple@0.1.1 start F:\Bot Samples\ibm\assistant-simple-m
aster
> node server.js

Server running on port: 3000
_http_server.js:208
    throw new ERR_HTTP_INVALID_STATUS_CODE(originalStatusCode);
    ^

RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: SELF_SIGNED_CERT
_IN_CHAIN
    at ServerResponse.writeHead (_http_server.js:208:11)
    at ServerResponse._implicitHeader (_http_server.js:199:8)
    at write_ (_http_outgoing.js:585:9)
    at ServerResponse.end (_http_outgoing.js:709:5)
    at ServerResponse.send (F:\Bot Samples\ibm\assistant-simple-master\node_modu
les\express\lib\response.js:221:10)
    at ServerResponse.json (F:\Bot Samples\ibm\assistant-simple-master\node_modu
les\express\lib\response.js:267:15)
    at F:\Bot Samples\ibm\assistant-simple-master\app.js:54:42
    at Request._callback (F:\Bot Samples\ibm\assistant-simple-master\node_module
s\watson-developer-cloud\lib\requestwrapper.js:61:13)
    at self.callback (F:\Bot Samples\ibm\assistant-simple-master\node_modules\wa
tson-developer-cloud\node_modules\request\request.js:185:22)
    at Request.emit (events.js:182:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ibm-watson/assistant-simple@0.1.1 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ibm-watson/assistant-simple@0.1.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\****\AppData\Roaming\npm-cache\_logs\2018-09-06T23_36_
04_281Z-debug.log

**Comment by mitchmason** [comment]
You can definitely do it on Windows. I dont have a windows machine rn but did on a Mac again just now. First, I edited my .env file, saved it, then ran npm install, then ran npm start. Got the message it was on localhost:3000, navigated there via my browser and it worked. 

Did you make any additional changes before running npm install?

**Comment by stevenpkg** [comment]
@sagarvadodaria also on top of what @mitchmason has told you above, are you executing npm install and npm start in the project root directory?

**Comment by sagarvadodaria** [comment]
I tried in my personal windows laptop and it just worked fine (barring few npm issues). I think for my work, since i am behind a corporate firewall and with a proxy, i get the errors above. i will close this issue, but if you any have suggestions for resolving "Invalid status code: SELF_SIGNED_CERT_IN_CHAIN", that would be much appreciated.
