### ISSUE TITLE
deploy to bluemix button

### ISSUE THREAD

**Issue by tkretsch** [watson-developer-cloud/assistant-simple#195]
Hello, thanks for sharing the project, it is very useful. could you add a deploy to bluemix button:
https://console.bluemix.net/docs/services/ContinuousDelivery/deploy_button.html#deploy-button
it would help to very quickly deploy more than 1 app for testing purposes. it would also be great if there would be a web online form to enter the data of the .env and manifest.yml ... hope it helps. thanks & greets.

**Comment by Oliver-I** [comment]
@stevenpkg Could you provide information on this issue.

**Comment by stevenpkg** [comment]
The preferred option is to use 'ibmcloud app push' command, We did used to have Deploy to IBM Cloud button, I will think about if we should bring it back.

**Comment by germanattanasio** [comment]
@stevenpkg is right we don't plan to support the deploy to IBM Cloud
