### ISSUE TITLE
write chat log to cloudant

### ISSUE THREAD

**Issue by tkretsch** [watson-developer-cloud/assistant-simple#196]
Hello, if you create a chatbot and you send it to colleagues & friends for testing purposes, you would need to see what has been asked and what has been answered. specifically for collecting questions it would be helpful to write the dialog into a cloudant. could you enhance the app in such a way? unfortunately I am not a developer :-) I am more a watson assistant creator. thanks a lot.

**Comment by Oliver-I** [comment]
@tkretsch The system allows you to examine the interactions via the Improve area. You can click on the Improve icon, then click on User Conversations to view the interactions between your virtual assistant and end-users - see screenshot below.




![image](https://user-images.githubusercontent.com/24578377/45276111-ca65d200-b503-11e8-8317-8e7d0be0e54f.png)
