### ISSUE TITLE
Support for Images and Pauses in App

### ISSUE THREAD

**Issue by alley28** [watson-developer-cloud/assistant-simple#198]
In working with the sample app - ive noticed two things it doesnt seem to support.  First, if i have conversation that has a pause in it - the app doesnt seem to honor that.  Also, if I have an image as part of a conversation response, it works inside of the Try it app in the Watson Assistant, but it doesnt seem like the app is able to handle the displaying of the image link.

**Comment by Oliver-I** [comment]
@alley28 These two items are currently being added to the app and should be available soon.

**Comment by alley28** [comment]
@Oliver-I Thanks for the note.  Not to be a pest, but is the timeline soon?  would love to showcase this as part of a lab we have for Dreamforce 2018.  That happens in a little over 2 weeks.

**Comment by germanattanasio** [comment]
Fixed in #200

**Comment by Oliver-I** [comment]
@alley28 These features are now in the code.
