### ISSUE TITLE
Reflected Cross-site Scripting Vulnerability

### ISSUE THREAD

**Issue by JStefanikIBM** [watson-developer-cloud/assistant-simple#199]
The app appears to suffer from an XSS vulnerability.

Writing the following payload to the chat will result in an alertbox displaying the domain that is hosting the Node.js app.

`<img` src=x onerror=alert(document.domain)><!--`

The Javascript code of the page is doing a request to /api/message and it uses the input:text to write the content into the chatbox message after the request is done.  This behaviour could allow an attacker to inject custom Javascript code that can be used to steal information from users or lure them to malicious websites.

**Comment by Oliver-I** [comment]
@stevenpkg Can you look into this?

**Comment by stevenpkg** [comment]
@JStefanikIBM demo apps are meant to be simple applications using Watson services, and not necessarily commercial strength apps, @mitchmason @germanattanasio  @fredrik-tunvall what do you all think?
