### ISSUE TITLE
Option to remove displaying of right hand side panel....

### ISSUE THREAD

**Issue by markpokane** [watson-developer-cloud/assistant-simple#203]
Hi Folks,

Is it possible to remove the right hand side panel showing the json calls? I'd like to make the demo available to a customer but only showing the interations with the chatbot.

Thanks and regards,
Mark

**Comment by markpokane** [comment]
Apologies but saw this was answered in a previous item. Closed accordingly.

**Comment by mitchmason** [comment]
I think this is what you're looking for:
https://github.com/watson-developer-cloud/assistant-simple/issues/68

**Comment by mitchmason** [comment]
@stevenpkg I actually this is either a) fairly common or b) something preventing from adopting this app more frequently, maybe we can add this to the readme so its more prominent?

**Comment by stevenpkg** [comment]
@mitchmason yes maybe we can add something to the readme to explain how to remove, or have some flag in the code to show and hide JSON?
