### ISSUE TITLE
Include local timezone in context

### ISSUE THREAD

**Issue by mitchmason** [watson-developer-cloud/assistant-simple#209]
Currently the time zone defaults to wherever the application is hosted (I think) and using functions like .now doesnt really help the end user, as they are likely not based in the same time zone as the application.
If we can send in users timezone as context this is easily fixed. 
https://console.bluemix.net/docs/services/conversation/supported-timezones.html#time-zones-supported-by-system-entities

**Comment by Oliver-I** [comment]
As discussed, we may look into this at a future date.
