### ISSUE TITLE
Handle audio with speech to text 🎙 and text to speech 🔊

### ISSUE THREAD

**Issue by Juleffel** [watson-developer-cloud/assistant-simple#210]
In case anyone wants to do that too, I post my fork here:

I added Speech to text and Text to Speech to this demo, with inputs to start/stop and change the voices. Here is the fork: [Juleffel/assistant-audio](https://github.com/Juleffel/assistant-audio) . You can see it work [live here](http://watson-assistant-audio.eu-de.mybluemix.net/).

I used the [speech-javascript-sdk](https://github.com/watson-developer-cloud/speech-javascript-sdk) which seems to have some problems at this moment with IAM keys. To make my version work, I had to use the fork mentioned in [this issue](https://github.com/watson-developer-cloud/speech-javascript-sdk/issues/92), and the current solution might fail if you use IAM instead of user/password or the reverse, somewhere in the code.

I will try to update my solution when they do.

**Comment by germanattanasio** [comment]
@Juleffel That looks pretty cool! Thanks for sharing your work!
