### ISSUE TITLE
Doesn't work with the new assistant using Skill

### ISSUE THREAD

**Issue by laurentvinc** [watson-developer-cloud/assistant-simple#213]

**Comment by germanattanasio** [comment]
HI @laurentvinc, you are right. This demo works with Assistant v1 and not Assistant v2.

We will look into creating a new demo once V2 is leaves beta

**Comment by laurentvinc** [comment]
i am using brand new instance of watson assistant but the API V1 are still the same. so I expected to get something running with the right APIkey , url and workspace ID. 
am i wrong?

**Comment by Oliver-I** [comment]
@stevenpkg Can you look into this. The app is running without issue on https://assistant-simple.ng.bluemix.net/

**Comment by stevenpkg** [comment]
@laurentvinc what output are you seeing in the console from `npm start`?

**Comment by laurentvinc** [comment]
So finally it is running but with the credentials the variables
assistant_username=apikey
assistant_password = <apikey value> 
previously I used the variables
assistant_iam_apikey and assistant_url. in this case the application didn't success to reach the service.

that's fine now, but i am surprised by the application settings.

**Comment by germanattanasio** [comment]
I was able to run the application with the IAM APIKEY
Here is the content of my `.env` file
```
WORKSPACE_ID="0be7658a-lionel-messi-8092-334c7e2b8ccb"
ASSISTANT_IAM_APIKEY="XBxG6KpyGRmkBlnaXuSQfKBmNc4Au7_maradona"
ASSISTANT_URL="https://gateway-fra.watsonplatform.net/assistant/api"
```
