### ISSUE TITLE
Mobile Ready

### ISSUE THREAD

**Issue by tim-minter** [watson-developer-cloud/assistant-simple#214]
Hi, could we get a version that is mobile first/mobile optimised? I've been trying to tweet the css to make it work on an iPhone 7 but so far failing. I use this quite a lot in IBM demos and it is always accessed via mobile in a demo situation. People always struggle with entering the text (the first char always disappears off the screen for example) And scrolling up/across to see the result isn't great.

**Comment by Oliver-I** [comment]
@tim-minter We currently don't have a mobile version of this sample app, but you can see a list of the Sample Apps at the Watson Assistant documentation (https://console.bluemix.net/docs/services/assistant/sample-applications.html#sample-apps), any new Sample Apps will appear on that list.
