### ISSUE TITLE
update readme images and gif

### ISSUE THREAD

**Issue by mitchmason** [watson-developer-cloud/assistant-simple#215]
please update the gif in the readme to use the new banking content
and the image about provisioning should be update to be more recent as well

**Comment by Oliver-I** [comment]
@mitchmason The readme gif was updated a while back and is showing the banking content, you may need to clear your browser cache. Let me know if you still can't see the banking content.

**Comment by Oliver-I** [comment]
As discussed will close this for now and update step 5 image at a later date.
