### ISSUE TITLE
too many dialog nodes in the example, the training json file cannot be imported 

### ISSUE THREAD

**Issue by nnworkspace** [watson-developer-cloud/assistant-simple#216]
Hi,

Watson Assistant API is running under V2 currently and I am trying to bring up this demo using my free Lite plan. The problem is, I cannot import the bank_simple_workspace.json. The error message is: 

We could not import your Skill. Maximum dialog_nodes limit exceeded. Limit = 100.

Could you please simplify the example and make the json file importable for a Lite plan? Thanks in advance!

Regards,
Ning

**Comment by germanattanasio** [comment]
This demo only works with V1.

**Comment by nnworkspace** [comment]
Is there any Watson Assistant Nodejs client example application that actually runs with API V2?

**Comment by mitchmason** [comment]
so the version of the api doesn't actually matter for the service limits. You can use this sample UI all you want, you just need to use a different workspace. 

If you open up the Watson Assistant GUI, there is another sample skill in there called customer care that will work. And you can use that with this simple sample app.

**Comment by mitchmason** [comment]
We will port this demo over to v2 over time

**Comment by nnworkspace** [comment]
My biggest problem is to actually get a connection to the WA service at all. Because all the example WA apps I found uses workspace_id in the .env file to connect, but the new bluemix WA UI doesn't even let me create a workspace any more (now it's called "assistant"). I tried out the pizzeria WA application, the UI starts but the assistant cannot even initialize itself. 

I think we need an updated example of the .env file.

**Comment by mitchmason** [comment]
skill id == workspace id

**Comment by Oliver-I** [comment]
@nnworkspace You can find smaller samples of the skill (workspace) at https://github.com/Oliver-I/Watson_Assistant_Sample_Library.

Also, the Intermediate Sample App will be updated to V2 very soon (github at https://github.com/watson-developer-cloud/assistant-intermediate and UI demo at https://assistant-intermediate.ng.bluemix.net/)

**Comment by Oliver-I** [comment]
@nnworkspace The Intermediate Sample App has now been updated to use the V2 API - https://github.com/watson-developer-cloud/assistant-intermediate

**Comment by nnworkspace** [comment]
@Oliver-I 

Cool!!! I'll clone and try it out right away. By the way, many customers would like to containerize their applications and deploy them onto Kubernetes clusters. It would really nice to provide a Docker file in the application. 

<3 Thank you very much! <3
