### ISSUE TITLE
"I'm having trouble connecting to the server, please refresh the page"

### ISSUE THREAD

**Issue by sandra-calvo** [watson-developer-cloud/assistant-simple#223]
Hi, 

I keep getting the following message when I run my app:
"I'm having trouble connecting to the server, please refresh the page". 

I was going crazy trying to find the error when I tried the demo app and it has the same problem.
[demo app](https://assistant-simple.ng.bluemix.net/)

Is there something wrong with the code?

Thanks.

**Comment by germanattanasio** [comment]
Please provide a set of reproducible steps.

**Comment by sandra-calvo** [comment]
sorry, my fault. My Watson Assistant was still v1, so once I used the v1 code it worked. 
Thanks.
