### ISSUE TITLE
I'm having trouble connecting to the server

### ISSUE THREAD

**Issue by binerb14** [watson-developer-cloud/assistant-simple#227]
Wir können vom User-interface nach der Eingabe keine Verbindung zum Chatbot bekommen.

Der Chatbot ist eingerichtet (trainiert) , d h. der Schritt "Watson Assistent Service" Instanz wurde erfolgreich durchgeführt. Er wurde erfolgreich auf der IBM-Cloud getestet.

Als nächster Schritt wurde das github Projekt heruntergeladen, die Dateien (URL, APIKEY usw) angepasst und die Client-Anwendung gestartet.

Allerdings bekommen ich im Client nach dem Absenden des Eingabe-Textes einen Verbindungsfehler!
![chrome_2019-02-11_12-17-31](https://user-images.githubusercontent.com/22678235/52559929-19879a00-2df7-11e9-8f82-39e79aab71ac.png)
![chrome_2019-02-11_12-16-24](https://user-images.githubusercontent.com/22678235/52559930-1a203080-2df7-11e9-8a53-9ecce3083872.png)

**Comment by Oliver-I** [comment]
@binerb14 Some other users have suggested to make sure that you don't have the old service credentials in your environment still (i.e. ASSISTANT_USERNAME, ASSISTANT_PASSWORD, etc.) .

@stevenpkg Please advise if this may be due to a different issue.

**Comment by stevenpkg** [comment]
@binerb14 please remove the assistant_url and you should be all good

**Comment by germanattanasio** [comment]
@binerb14 `ASSISTANT_IAM_URL` is wrong. Remove it and it will work
