### ISSUE TITLE
I'm having trouble connecting to the server, please refresh the page

### ISSUE THREAD

**Issue by cauems** [watson-developer-cloud/assistant-simple#245]
Which of these credentials do I put in the code and where do I find them in current Watson?
(assistant feature)

![image](https://user-images.githubusercontent.com/53436391/64786409-be608600-d544-11e9-814d-58a49f6a8ed5.png)

**Comment by Oliver-I** [comment]
@cauems If you are still experiencing issues, take a look here - https://github.com/watson-developer-cloud/assistant-simple/issues/224.

**Comment by Oliver-I** [comment]
@cauems This issue will now be closed. If you are still experiencing the problem please re-open the issue for further assistance.
