### ISSUE TITLE
Skills with DISCOVERY-IT DON'T SHOW THE ANSWER

### ISSUE THREAD

**Issue by JoseAvalos** [watson-developer-cloud/assistant-simple#246]
Hello

I has been working ok with that assistant. I added a skill base in Discovery service that it's working fine in integration demo. However, using this github the chatbot just respond to dialog assistant but no with Discovery assistant responding "I'm having trouble connecting to the server, please refresh the page"

I have notice that in right screen I receive the answer but it did show in the user space.

![Screenshot_6](https://user-images.githubusercontent.com/9720513/64882919-bb889280-d623-11e9-8bfa-b8f76922747e.png)

**Comment by Oliver-I** [comment]
@JoseAvalos That's correct, the assistant-simple does not have Search integration. What you need is the assistant-intermediate version, which can be found at https://github.com/watson-developer-cloud/assistant-intermediate.

You can test the Intermediate app at https://assistant-intermediate.ng.bluemix.net/ . Simply type "insurance" and it will display a list of search results.
