### ISSUE TITLE
Adding code to filter the response

### ISSUE THREAD

**Issue by Mmalik83** [watson-developer-cloud/assistant-simple#252]
Hi 

I am using Watson discovery via webhook to Watson Assistant to bring the passages from discovery results. I want to add some code to the data received from the assistant to filter out unnecessary fields such as document_id etc from the passages. Where can i put the following code to filter "text" field in passages. 

/**
 * formatData - format search results into items we can process easier. This includes
 * 1) only keeping fields we show in the UI
 * 2) highlight matching words in text
 * 3) if showing 'passages', ignore all other results
 */
function formatData(data) {
  var formattedData = {};
  var newPassages = [];

  var count = 0;
  data.forEach(function(dataItem) {
    // only keep the data we show in the UI.
    if (dataItem.field === 'text') {
      count = count + 1;
      var newPassage = {
        id: count,
        text: dataItem.passage_text,
        score: dataItem.passage_score,
      };
      newPassages.push(newPassage);
    }
  });

  formattedData.results = newPassages;
  console.log('Formatting Data: size = ' + newPassages.length);
  return formattedData;
}

module.exports = {
  objectWithoutProperties,
  formatData
};

**Comment by Oliver-I** [comment]
@Mmalik83 You can see how the Search Doc results are handled in the Intermediate Sample App - https://github.com/watson-developer-cloud/assistant-intermediate/blob/master/functions/searchDocs.js . The Simple App doesn't handle Search Docs.
