### ISSUE TITLE
Uncaught TypeError: Cannot read property 'session_id' of undefined

### ISSUE THREAD

**Issue by marcelodiaz558** [watson-developer-cloud/assistant-simple#258]
Hello, I'm trying to deploy the Node JS server to a Namecheap hosting, everything is working fine in my local computer but when I deploy and everything is configured then I receive the following error locally: 
```
Uncaught TypeError: Cannot read property 'session_id' of undefined at 
XMLHttpRequest.http.onreadystatechange (api.js:42)
```

All my UI charges ok and my bot answers with the habitual "I'm having trouble connecting to the server, please refresh the page", apparently is a problem related with the session_id, I've looked into the code but since I'm not very proficient in javascript I couldn't identify the problem myself, any help? Please. 

The piece of code in api.js with the problem is the following:
```js
  function getSessionId(callback) {
    var http = new XMLHttpRequest();
    http.open('GET', sessionEndpoint, true);
    http.setRequestHeader('Content-type', 'application/json');
    http.onreadystatechange = function () {
      if (http.readyState === XMLHttpRequest.DONE) {
        let res = JSON.parse(http.response);
        sessionId = res.result.session_id;
        callback();
      }
    };
    http.send();
  }
``` 
And the HTTP error code is 500 (internal server error), in my server side the passenger.log file doesn't log any error.
![Captura de pantalla (10)](https://user-images.githubusercontent.com/40875838/79609290-7dc18000-80c4-11ea-9e2f-530e74ed32f4.png)

**Comment by germanattanasio** [comment]
What's the output of `rest.result` if you print it out? It's hard to understand what the problem is without a set of reproducible steps

**Comment by marcelodiaz558** [comment]
> What's the output of `rest.result` if you print it out? It's hard to understand what the problem is without a set of reproducible steps

Thanks for answering, `res` was an empty JSON like format, I already solved this problem, it was a quite simple mistake on my side, to try to be helpful this is what was happening:

After deploying the server to my web hosting I forgot about changing the sessionEndPoint and messageEndPoint variables in api.js, it's important because now that our web app is on the internet we need to specify https://ourwebpage.com/api/session instead of just /api/session, also since my hosting had a WordPress installation in a prior point of time it was conflicting with the /api/session and /api/message routes throwing a 500 internal server error.
